name: GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build .NET App
        run: dotnet build

      - name: Publish application
        run: dotnet publish -c Release -o publish/

      - name: Copy files to server
        uses: appleboy/scp-action@main
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: publish/
          target: ${{ env.REMOTE_DIRECTORY }}
